{% set version = "5.1.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcppparallel
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppParallel_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppParallel/RcppParallel_{{ version }}.tar.gz
  sha256: d655b18ad85655e3df9313695a46e7ba6c8c0b5576ff1ab50010b34a97bba126

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('r_clang') }}    # [win]
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}        # [not win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - tbb-devel
  run:
    - r-base
    - tbb-devel

test:
  commands:
    - $R -e "library('RcppParallel')"           # [not win]
    - "\"%R%\" -e \"library('RcppParallel')\""  # [win]

about:
  home: http://rcppcore.github.io/RcppParallel
  dev_url: https://github.com/RcppCore/RcppParallel
  license: GPL-3.0-or-later
  summary: High level functions for parallel programming with 'Rcpp'. For example, the 'parallelFor()' function can be used to convert the work of a standard serial "for" loop into a parallel one and the 'parallelReduce()' function can be used for accumulating aggregate or other values.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
