{% set version = "5.1.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcppparallel
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppParallel_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppParallel/RcppParallel_{{ version }}.tar.gz
  sha256: fd0861f3f0f7be4e0ef29c021e75beb351ae2eb18ce5d79e21f2725da4da114f

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  script_env:       # [aarch64 or arm64 or ppc64le]
    - arch=aarch64  # [aarch64]
    - arch=arm64    # [arm64]
    - arch=ppc64    # [ppc64le]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  requires:
    - {{ posix }}make     # [win]
    - r-rcpp
    - r-runit
  source_files:
    - tests/
  commands:
    - $R -e "library('RcppParallel')"                                        # [not win]
    - RCPP_PARALLEL_BACKEND=tbb Rscript tests/doRUnit.R                      # [not win]
    - RCPP_PARALLEL_BACKEND=tinythread Rscript tests/doRUnit.R               # [not win]
    - "\"%R%\" -e \"library('RcppParallel')\""                               # [win]
    - "set \"RCPP_PARALLEL_BACKEND=tbb\" && Rscript tests/doRUnit.R"         # [win]
    - "set \"RCPP_PARALLEL_BACKEND=tinythread\" && Rscript tests/doRUnit.R"  # [win]

about:
  home: http://rcppcore.github.io/RcppParallel
  dev_url: https://github.com/RcppCore/RcppParallel
  license: GPL-3.0-or-later
  summary: High level functions for parallel programming with 'Rcpp'. For example, the 'parallelFor()' function can be used to convert the work of a standard serial "for" loop into a parallel one and the 'parallelReduce()' function can be used for accumulating aggregate or other values.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
