travis:
  secure:
    BINSTAR_TOKEN: mE5tMfSB4JBDsHEnp+4F7SkwsW7XgBLJe1hTOkmDD31rOzZzi1I/0L5lOrHrvZHyt22F7Z2473Sa/8hBn8azwvhJAcGW4HTK/2RVpbOi0WeK+Odz6NJzhE028BdXZs2nYAMTLnQHyfbseXm2RtIt/AqojeU9BSY3t+e05+PqCKF5S1dYtCWGapNktHiHk5IW8XUuO1zi81QdYKgrz5gTsThW24mkb4HSYqtrS1F0Y4VIibQrbK71thTyu6AUkjaa2J2ghH0rpuK1ZMBWnLcmVIOGwZTawiIw6glITIMhpU9ELrxwbz5WQoipOMC8bTcVTOfkUaWtuWZMRDuF5cmuts5Weh1gbAA4biLsEmboZG0Lip4tXZdKyoXlh4zuBuyWBgH4RnvjlUNsTScS1tOHshzMncIq39rnGsfpyDQ8ZHQaV98c0V2SxRFFBwiT5qAR3si/yLprJVX9NCorkCOXiDogxYtk4rbcpx1pGvnU10uTCqrRlzkCGs4lkoBvp/x8LbavRa1uWLVKpFWWbJJIrLpHCfwUNFjRtC8R5pVLG2M5hrHT1xkpWh9CKof0nJaeLwO9zTfNXoWH6crX8SvygS8CDcbdRH+/Ig/5vOWyBKAPMeZXWeo3pwvfBk0aAlR/WJN8Og+Ev6S9/CsXw7vFuFxjaxFXTKiEasAYbQGZBnE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: false
